services:
  fraud_detection_app-backend-1:
    #build:
     # context: ./backend
    image: mouskam/backend-app:latest
    ports:
      - "5010:5010"
    #volumes:
    #  - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - fraudapp-network
    restart: always

  frontend:
    #build:
      #context: ./frontend
    image: mouskam/frontend-app:latest
    ports:
      - "3010:3010"
    #volumes:
    #  - ./frontend:/app
    depends_on:
      - fraud_detection_app-backend-1
    networks:
      - fraudapp-network

networks:
  fraudapp-network:
    driver: bridge